admins: chunyu.zhao@czbiohub.org


species_id: 100001
base_dir: /mnt/cz/20210414_species_w_isolates
lib_dir: /mnt/cz/iggtools-reads-mapping

bt2_combo_fp: bt2_combo.tsv

threads: 4

## art
sim_cov: "51"
read_length: 125
frag_length: 400
frag_std: 40


##
min_allele_depth: 2
