admins: chunyu.zhao@czbiohub.org


species_id: 100001
base_dir: /mnt/cz/20201110_species_w_isolates
lib_dir: /mnt/cz/iggtools-reads-mapping

bt2_combo_fp: bt2_combo.tsv

threads: 1

## art
sim_cov: "50"
read_length: 125
frag_length: 400
frag_std: 40
